#
# linux/drivers/rknand/Makefile
#
# $Id: Makefile,v 1.3 2011/01/21 10:12:56 Administrator Exp $
#
obj-$(CONFIG_MTD_NAND_RK29XX)		+= rknand_base.o flash.o ftl.o emmc.o rknand_buffer.o kernel_lock.o





